"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""

a = 1
b = 1
total = 0

while (a < 4000000):
	a += b
	b += a

	if (a < 4000000 and a % 2 == 0):
		total += a
	if (b < 4000000 and b % 2 == 0):
		total += b

print(total)